python3 train_multimodal.py --gpu_num 3 --dist 1  --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1
python3 train_multimodal.py --gpu_num 3 --dist 2  --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1
python3 train_multimodal.py --gpu_num 3 --dist 3  --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1
python3 train_multimodal.py --gpu_num 3 --dist 4  --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1 
python3 train_multimodal.py --gpu_num 3 --dist 5  --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1
python3 train_multimodal.py --gpu_num 3 --dist 8  --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1 
python3 train_multimodal.py --gpu_num 3 --dist 12 --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1
python3 train_multimodal.py --gpu_num 3 --dist 16 --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1
python3 train_multimodal.py --gpu_num 3 --dist 20 --num_epoch 128 --batch_size 64 --loss_type 'Focal' --use_sampling '' --use_weighting '' --use_DRW 1