python3 train_multimodal.py --gpu_num 3 --dist 1 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 2 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 3 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 4 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 5 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 8 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 12 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 16 --use_GB True
python3 train_multimodal.py --gpu_num 3 --dist 20 --use_GB True