python3 plot_model_structure.py --model 'Transformer'
python3 plot_model_structure.py --model 'CnnLSTM'
python3 plot_model_structure.py --model 'MLSTM_FCN'
python3 plot_model_structure.py --model 'ViViT'
python3 plot_model_structure.py --model 'R2Plus1D'
python3 plot_model_structure.py --model 'SlowFast'