# python3 train_0D_network.py --dist 1 --gpu_num 3 --model 'Transformer' --tag 'Transformer'
# python3 train_0D_network.py --dist 2 --gpu_num 3 --model 'Transformer' --tag 'Transformer'
# python3 train_0D_network.py --dist 3 --gpu_num 3 --model 'Transformer' --tag 'Transformer'
# python3 train_0D_network.py --dist 4 --gpu_num 3 --model 'Transformer' --tag 'Transformer'
# python3 train_0D_network.py --dist 5 --gpu_num 3 --model 'Transformer' --tag 'Transformer'

# python3 train_0D_network.py --dist 1 --gpu_num 3 --model 'CnnLSTM' --tag 'CnnLSTM'
# python3 train_0D_network.py --dist 2 --gpu_num 3 --model 'CnnLSTM' --tag 'CnnLSTM'
# python3 train_0D_network.py --dist 3 --gpu_num 3 --model 'CnnLSTM' --tag 'CnnLSTM'
# python3 train_0D_network.py --dist 4 --gpu_num 3 --model 'CnnLSTM' --tag 'CnnLSTM'
# python3 train_0D_network.py --dist 5 --gpu_num 3 --model 'CnnLSTM' --tag 'CnnLSTM'

python3 train_0D_network.py --dist 1 --gpu_num 0 --model 'MLSTM_FCN' --tag 'MLSTM_FCN'
python3 train_0D_network.py --dist 2 --gpu_num 0 --model 'MLSTM_FCN' --tag 'MLSTM_FCN'
python3 train_0D_network.py --dist 3 --gpu_num 0 --model 'MLSTM_FCN' --tag 'MLSTM_FCN'
python3 train_0D_network.py --dist 4 --gpu_num 0 --model 'MLSTM_FCN' --tag 'MLSTM_FCN'
python3 train_0D_network.py --dist 5 --gpu_num 0 --model 'MLSTM_FCN' --tag 'MLSTM_FCN'