python3 train_vision_network.py --gpu_num 0 --dist 1 --batch_size 32 --model 'ViViT' --tag 'ViViT'
python3 train_vision_network.py --gpu_num 0 --dist 2 --batch_size 32 --model 'ViViT' --tag 'ViViT'
python3 train_vision_network.py --gpu_num 0 --dist 3 --batch_size 32 --model 'ViViT' --tag 'ViViT'
python3 train_vision_network.py --gpu_num 0 --dist 4 --batch_size 32 --model 'ViViT' --tag 'ViViT'
python3 train_vision_network.py --gpu_num 0 --dist 5 --batch_size 32 --model 'ViViT' --tag 'ViViT'